In [1]:
import numpy as np

In [2]:
np.full((2, 2), 8)

array([[8, 8],
       [8, 8]])

### 随机数

In [4]:
np.random.rand(2, 4)

array([[0.17850625, 0.22504245, 0.58420739, 0.89283887],
       [0.55954993, 0.37485777, 0.51872114, 0.92913273]])

In [5]:
np.random.rand()

0.22292312394566882

In [6]:
np.random.randint(1, 10, (2, 2))

array([[8, 2],
       [1, 4]])

In [7]:
np.random.randn(2, 4)

array([[-0.84946428, -0.24646838,  0.60483319,  0.43396039],
       [ 0.72729347,  0.89786167, -1.77261328,  0.22845212]])

In [8]:
np.random.choice([1, 2, 3])

3

In [9]:
np.random.choice([1, 2, 3], (2, 2))

array([[3, 3],
       [2, 1]])

In [11]:
np.arange(1, 18, 2).reshape((3, 3))

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [21]:
a = np.full((3, 3), 2)
b = np.arange(9).reshape((3, 3))

In [22]:
np.concatenate([a, b])

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
np.concatenate([a, b], axis=1)

array([[2, 2, 2, 0, 1, 2],
       [2, 2, 2, 3, 4, 5],
       [2, 2, 2, 6, 7, 8]])

In [24]:
np.stack([a, b])

array([[[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]],

       [[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [26]:
np.stack([a, b], axis=1)

array([[[2, 2, 2],
        [0, 1, 2]],

       [[2, 2, 2],
        [3, 4, 5]],

       [[2, 2, 2],
        [6, 7, 8]]])

In [27]:
np.vstack([a, b])

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
np.hstack([a, b])

array([[2, 2, 2, 0, 1, 2],
       [2, 2, 2, 3, 4, 5],
       [2, 2, 2, 6, 7, 8]])

### 线性代数

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
a = np.random.rand(3, 3)
a

array([[0.76070146, 0.80953909, 0.55203283],
       [0.65486552, 0.77617201, 0.50650357],
       [0.9403639 , 0.77017368, 0.6011035 ]])

In [62]:
np.linalg.matrix_rank(a)

3

In [61]:
np.linalg.det(a)

0.0005826803195498859

In [60]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
a_inv = np.linalg.inv(a)
a_inv

array([[ 131.22804443, -105.47057611,  -31.64341183],
       [ 141.85430348, -106.1498491 ,  -40.82983249],
       [-387.04576734,  301.0039723 ,  103.48032276]])

In [39]:
a @ a_inv

array([[1.00000000e+00, 1.75805183e-15, 0.00000000e+00],
       [8.39378229e-15, 1.00000000e+00, 0.00000000e+00],
       [2.84217094e-14, 0.00000000e+00, 1.00000000e+00]])

In [40]:
a.transpose()

array([[0.76070146, 0.65486552, 0.9403639 ],
       [0.80953909, 0.77617201, 0.77017368],
       [0.55203283, 0.50650357, 0.6011035 ]])

In [41]:
a.T

array([[0.76070146, 0.65486552, 0.9403639 ],
       [0.80953909, 0.77617201, 0.77017368],
       [0.55203283, 0.50650357, 0.6011035 ]])

In [42]:
np.linalg.eig(a)

(array([2.10248015, 0.01159482, 0.02390201]),
 array([[ 0.57472213,  0.25200382, -0.19191797],
        [ 0.52386304,  0.37511697, -0.4276743 ],
        [ 0.62869865, -0.89206577,  0.88332451]]))

In [43]:
np.linalg.svd(a)

(array([[-0.57541216, -0.26814571, -0.77265692],
        [-0.52498311, -0.60331122,  0.60034016],
        [-0.62713123,  0.75107486,  0.20638065]]),
 array([2.15463379e+00, 1.51411515e-01, 1.78606796e-03]),
 array([[-0.63641524, -0.62947857, -0.44579409],
        [ 0.70811747, -0.7059544 , -0.01407282],
        [-0.30585176, -0.32463074,  0.89502491]]))

In [48]:
y = np.full((3), 1)

In [49]:
np.linalg.solve(a, y)

array([-5.88594351, -5.1253781 , 17.43852772])

In [50]:
yy = np.expand_dims(y, 0)
yy

array([[1, 1, 1]])

In [51]:
np.squeeze(yy)

array([1, 1, 1])

In [52]:
a

array([[0.76070146, 0.80953909, 0.55203283],
       [0.65486552, 0.77617201, 0.50650357],
       [0.9403639 , 0.77017368, 0.6011035 ]])

In [53]:
np.unique(a)

array([0.50650357, 0.55203283, 0.6011035 , 0.65486552, 0.76070146,
       0.77017368, 0.77617201, 0.80953909, 0.9403639 ])

In [54]:
a_sub = a[:, 0]
a_sub

array([0.76070146, 0.65486552, 0.9403639 ])

In [55]:
np.isin(a_sub, a)

array([ True,  True,  True])

In [56]:
nan = np.array([1, 2, np.nan])
nan

array([ 1.,  2., nan])

In [57]:
np.nan_to_num(nan)

array([1., 2., 0.])